---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    login_info:
      host: "{{ ansible_host }}"
      username: "{{ ansible_username }}"
      password: "{{ ansible_password }}"
  pre_tasks:
    - assert:
        that: vlan_id is defined
        msg: "vlan_id is not included as an extra var"
  roles:
    - role: trunk
